apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer0-pvc
spec:
  storageClassName: local-storage-orderer
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi