apiVersion: v1
kind: Service
metadata:
  name: couchdb0-service
spec:
  selector:
    app: couchdb0
    tier: database
  ports:
    - protocol: TCP
      targetPort: couchdb0-port
      port: 5984
      nodePort: 30005
      name: couchdb0-port
  type: NodePort
